SELECT E.ID AS ID, IFNULL(C.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) C ON E.ID = C.PARENT_ID
ORDER BY ID
