SELECT I.ITEM_ID AS ITEM_ID, I.ITEM_NAME AS ITEM_NAME, I.RARITY AS RARITY 
FROM ITEM_INFO I
WHERE I.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID FROM ITEM_TREE
    WHERE 1 = 1 and PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC
