SELECT F.ID AS ID, FNI.FISH_NAME AS FISH_NAME, F.LENGTH AS LENGTH 
FROM FISH_INFO F
RIGHT JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
    GROUP BY FISH_TYPE
) FT ON FT.LENGTH = F.LENGTH AND FT.FISH_TYPE = F.FISH_TYPE
LEFT JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = F.FISH_TYPE
WHERE 1 = 1 ORDER BY ID ASC
